apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-app-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: backend-engine
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1